#include "print_transports.h"
#include <WiFi.h>
#include <string.h>

static bool connectClient(WiFiClient& c, const PrintTarget& t, uint16_t fallback, uint32_t timeout) {
  c.setTimeout(timeout / 1000 + 1); uint16_t port = t.port ? t.port : fallback;
  if (t.address != IPAddress(0, 0, 0, 0)) return c.connect(t.address, port, timeout);
  return !t.host.isEmpty() && c.connect(t.host.c_str(), port, timeout);
}
static bool writeAll(WiFiClient& c, const uint8_t* d, size_t n) {
  size_t sent=0; while(sent<n){size_t w=c.write(d+sent,n-sent);if(!w)return false;sent+=w;yield();}return true;
}
static bool writeStream(WiFiClient& c, Stream& source, size_t n) {
  uint8_t b[1460];size_t left=n;while(left){size_t want=left<sizeof(b)?left:sizeof(b);size_t got=source.readBytes((char*)b,want);if(got!=want||!writeAll(c,b,got))return false;left-=got;yield();}return true;
}
bool Raw9100Transport::send(const PrintTarget& t,const uint8_t*d,size_t n,uint32_t timeout){if(!d||!n)return false;WiFiClient c;if(!connectClient(c,t,9100,timeout))return false;bool ok=writeAll(c,d,n);c.flush();delay(20);c.stop();return ok;}
bool Raw9100Transport::sendStream(const PrintTarget&t,Stream&source,size_t n,uint32_t timeout){if(!n)return false;WiFiClient c;if(!connectClient(c,t,9100,timeout))return false;bool ok=writeStream(c,source,n);c.flush();delay(20);c.stop();return ok;}
static void put16(uint8_t*p,uint16_t v){p[0]=v>>8;p[1]=v;}static void put32(uint8_t*p,uint32_t v){p[0]=v>>24;p[1]=v>>16;p[2]=v>>8;p[3]=v;}
static bool attr(uint8_t*b,size_t cap,size_t&pos,uint8_t tag,const char*name,const uint8_t*v,size_t n){size_t nl=strlen(name);if(nl>65535||n>65535||pos+5+nl+n>cap)return false;b[pos++]=tag;put16(b+pos,nl);pos+=2;memcpy(b+pos,name,nl);pos+=nl;put16(b+pos,n);pos+=2;if(n)memcpy(b+pos,v,n);pos+=n;return true;}
static bool sattr(uint8_t*b,size_t cap,size_t&pos,uint8_t tag,const char*n,const String&v){return attr(b,cap,pos,tag,n,(const uint8_t*)v.c_str(),v.length());}
bool IppTransport::buildPrintJobRequest(uint8_t*b,size_t cap,size_t&length,const String&uri,const String&user,uint32_t requestId,const uint8_t*d,size_t n){length=0;if(!b||!d||!uri.length()||n>cap||cap<128)return false;size_t p=0;b[p++]=1;b[p++]=1;put16(b+p,2);p+=2;put32(b+p,requestId);p+=4;b[p++]=1;if(!sattr(b,cap,p,0x47,"attributes-charset","utf-8")||!sattr(b,cap,p,0x48,"attributes-natural-language","en")||!sattr(b,cap,p,0x45,"printer-uri",uri)||!sattr(b,cap,p,0x42,"requesting-user-name",user.isEmpty()?String("android"):user)||!sattr(b,cap,p,0x49,"document-format","application/octet-stream"))return false;if(p+1+n>cap)return false;b[p++]=3;memcpy(b+p,d,n);p+=n;length=p;return true;}
static bool buildIppHeader(uint8_t*b,size_t cap,size_t&length,const String&uri,const String&user,uint32_t requestId,const String&format){length=0;if(!b||!uri.length()||cap<128)return false;size_t p=0;b[p++]=1;b[p++]=1;put16(b+p,2);p+=2;put32(b+p,requestId);p+=4;b[p++]=1;String fmt=format.isEmpty()?String("application/octet-stream"):format;if(!sattr(b,cap,p,0x47,"attributes-charset","utf-8")||!sattr(b,cap,p,0x48,"attributes-natural-language","en")||!sattr(b,cap,p,0x45,"printer-uri",uri)||!sattr(b,cap,p,0x42,"requesting-user-name",user.isEmpty()?String("esp32"):user)||!sattr(b,cap,p,0x49,"document-format",fmt))return false;b[p++]=3;length=p;return true;}
static bool readHttpStatusAndHeaders(WiFiClient&c,uint32_t timeoutMs){unsigned long deadline=millis()+timeoutMs;bool first=true;while((long)(deadline-millis())>0){if(!c.available()){delay(1);continue;}String line=c.readStringUntil('\n');line.trim();if(first){first=false;if(!(line.startsWith("HTTP/1.1 200")||line.startsWith("HTTP/1.0 200")))return false;}else if(line.isEmpty())return true;}return false;}
static bool readIppResponseStatus(WiFiClient&c,uint16_t*status,uint32_t timeoutMs){if(status)*status=0xFFFF;uint8_t h[8];size_t got=0;unsigned long deadline=millis()+timeoutMs;while(got<8&&(long)(deadline-millis())>0){if(!c.available()){delay(1);continue;}int n=c.read(h+got,8-got);if(n>0)got+=(size_t)n;}if(got!=8)return false;if(status)*status=((uint16_t)h[2]<<8)|h[3];return h[0]==1&&(h[1]==0||h[1]==1||h[1]==2);}
static bool sendIppStream(const PrintTarget&target,const String&uri,const String&user,const String&format,Stream&source,size_t length,uint32_t timeoutMs,uint16_t*status){if(!length||uri.isEmpty())return false;WiFiClient c;if(!connectClient(c,target,631,timeoutMs))return false;c.setTimeout(timeoutMs/1000+1);uint8_t header[1024];size_t headerLength=0;if(!buildIppHeader(header,sizeof(header),headerLength,uri,user,millis()|1UL,format)){c.stop();return false;}int scheme=uri.indexOf("://");int slash=scheme>=0?uri.indexOf('/',scheme+3):-1;String path=slash>=0?uri.substring(slash):String("/ipp/print");if(path.isEmpty())path="/ipp/print";c.print("POST ");c.print(path);c.print(" HTTP/1.1\r\nHost: ");if(target.host.length())c.print(target.host);else c.print(target.address.toString());c.print("\r\nContent-Type: application/ipp\r\nContent-Length: ");c.print((unsigned long)(headerLength+length));c.print("\r\nConnection: close\r\n\r\n");if(!writeAll(c,header,headerLength)||!writeStream(c,source,length)){c.stop();return false;}c.flush();if(!readHttpStatusAndHeaders(c,timeoutMs)){c.stop();return false;}bool ok=readIppResponseStatus(c,status,timeoutMs);c.stop();return ok&&(!status||*status==0);}
bool IppTransport::sendStream(const PrintTarget&t,const String&uri,const String&user,const String&format,Stream&source,size_t length,uint32_t timeoutMs,uint16_t*status){return sendIppStream(t,uri,user,format,source,length,timeoutMs,status);}
bool IppTransport::send(const PrintTarget&t,const String&uri,const String&user,const String&format,const uint8_t*document,size_t length,uint32_t timeoutMs,uint16_t*status){if(!document||!length)return false;class MemoryStream:public Stream{public:MemoryStream(const uint8_t*d,size_t n):d_(d),n_(n){}int available()override{return(int)(n_-p_);}int read()override{return p_<n_?d_[p_++]:-1;}int peek()override{return p_<n_?d_[p_]:-1;}void flush()override{}size_t write(uint8_t)override{return 0;}size_t readBytes(char*b,size_t n)override{size_t k=n<n_-p_?n:n_-p_;if(k)memcpy(b,d_+p_,k);p_+=k;return k;}private:const uint8_t*d_;size_t n_;size_t p_=0;}source(document,length);return sendStream(t,uri,user,format,source,length,timeoutMs,status);}
